<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<?php $dataHelper = $this->helper('Magezon\LazyLoad\Helper\Data') ?>
<img class="photo image <?= $dataHelper->getLazyClasses() ?>"
    <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
    data-src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
    width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
    height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
    alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>" />
