<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<?php $dataHelper = $this->helper('Magezon\LazyLoad\Helper\Data') ?>

<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100) ?>%;">
        <img class="product-image-photo <?= $dataHelper->getLazyClasses() ?>"
            <?= /* @escapeNotVerified */ $block->getCustomAttributes() ?>
            data-src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
            width="<?= /* @escapeNotVerified */ $block->getResizedImageWidth() ?>"
            height="<?= /* @escapeNotVerified */ $block->getResizedImageHeight() ?>"
            alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>
