<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module?>
	<?php
		$tvHelper = $this->helper('Themevast\Themevast\Helper\Data');
		$show_shortdescription = $block->getConfig('description')==1 ? true:false;
		$length = $block->getConfig('maxlength') ? $block->getConfig('maxlength'):50;
		$_productCollection = $this->getProducts();
		$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<?php			
		$viewMode = 'grid';
		$image = 'category_page_grid';
		$showDescription = false;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		$pos = $block->getPositioned();
	?>
	<div class="featured_products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
		
		<?php if($this->getConfig('title')){?>
			<div class="block-title title-featured-heading">
				<strong><?php echo $this->getConfig('title')?></strong>
				<p><?php echo __('We search high and low to bring you the coolest stuff around. ') ?><br>
					<?php echo __('Fill your closet with our newest.. ') ?>.</p>
			</div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="message info empty">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			if(!$rows = $this->getConfig('items_show'))
				$rows = 2;
			?>	
				<div class="owl-carousel product-items">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<div class='item featured-item clearfix'>"; ?>
						<div class="product-item">
							<div class="product-item-info" data-container="product-grid">
								<?php // Product Image ?>
		                        <?php
			                        $productImage = $block->getImage($_product, $image);
			                        if ($pos != null) {
			                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
			                                . 'top:' . $productImage->getHeight() . 'px;"';
			                        }
		                        ?>
								<div class="product-images">
		                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
		                                <?php echo $productImage->toHtml(); ?>
		                            </a>
							        <?php
			                             $specialprice = $_product->getSpecialPrice();
			                             $specialPriceFromDate = $_product->getSpecialFromDate();
			                             $specialPriceToDate = $_product->getSpecialToDate();
			                             $_price=$_product->getPrice();
			                             $_finalPrice=$_product->getFinalPrice();
			                             $today = time();?>
			                    
			                             <?php 
			                             if ($specialprice) {
			                              if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
			                               <span class="label-product label-sale">
			                                    <?php if($_finalPrice < $_price): ?>
			                                      <?php $_savePercent = 100 - round(($_finalPrice / $_price)*100); ?>
			                                        <?php echo __('Sale');?>
			                                      <?php endif; ?>
			                               </span>
			                              <?php }
			                             }
			                             ?>
			                             <?php
			                             $now = date("Y-m-d");
			                             $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
			                             $newsTo = substr($_product->getNewsToDate(), 0, 10);

			                             if (($newsTo != '' || $newsFrom != '') && !$specialprice) {
			                             if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
			                               <span class="label-product label-new"><?php echo __('New'); ?></span>
			                             <?php }
			                        } ?>
								    <?php if( $this->getConfig('addtowishlist')): ?>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<a href="#"
											class="action towishlist"
										   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
										   data-action="add-to-wishlist"
										   role="button">
											<i class="fa fa-heart"></i>
										</a>
										<?php endif; ?>
									<?php endif; ?>
								    <div class="quickview-product">
		                                <a data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="" class="ajax diamond quick-view" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
		                                <?php echo $block->escapeHtml(__('Quick View')); ?>
		                                </a>
		                            </div>
		                            <div class="product-group-details">
		                            	<?php if($this->getConfig('review')): ?>
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
										<?php endif; ?>
		                            	<?php
											$_productNameStripped = $block->stripTags($_product->getName(), null, true);
										?>
										<strong class="product name product-item-name">
											<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
												<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
											</a>
										</strong>
										<?php if( $this->getConfig('show_price') ): ?>
											<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
										<?php endif; ?>
										<?php if ($this->getConfig('addtocart')) { ?>
											<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button class="action tocart primary" type="submit"
													title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" >
															<span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
														<button class="action tocart primary stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></button>
													<?php else: ?>
														<button class="action tocart primary stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></button>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										<?php }?>
		                            </div>
		                        </div>
								<div class="product details product-item-details">
									<strong class="product name product-item-name">
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</strong>
									<?php if( $this->getConfig('show_price') ): ?>
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<?php endif; ?>
									<a class="shop-now" href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"><?php echo $block->escapeHtml(__('Shop now')); ?><i class="fa fa-caret-right"></i></a>
								</div>
							</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>                
				</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
		<script type="text/javascript">
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';

					jQuery(".featured_products .owl-carousel").owlCarousel({
						autoplay :false,
						items : 4,
						smartSpeed : 500,
						dotsSpeed : 500,
						rewindSpeed : 500,
						nav : true,
						autoplayHoverPause : true,
						dots : false,
						scrollPerPage:true,
						navText: ['<i class="envy-icon envy-icon-left"></i>','<i class="envy-icon envy-icon-right"></i>'],
						margin: 30,
						responsive: {
						0: {
							items: 1,
						},
						480: {
							items:2,
						},
						768: {
							items:2,
						},
						991: {
							items:3,
						},						
						1200: {
							items:4,
						}
					 }
					});
					$(".featured_products .owl-stage-outer").hover(function(){
				        $(this).css("padding", "10px 10px 200px").css("margin", "-10px -10px -200px");
				        }, function(){
				        $(this).css("padding", "0").css("margin", "0");
				    });
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>