<?php
$element  = $this->getElement();
$numPosts = (int)$element->getData('num_posts') ? (int)$element->getData('num_posts') : 5;
$boxWidth = $element->getData('box_width');
$pageUrl  = $element->getData('page_url');
?>
<div class="fb-comments" data-url="<?= $pageUrl ?>" data-numposts="<?= $numPosts ?>" data-width="100%"></div>
<script>(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>