<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php

if ($exist = $block->getItems()->getSize()) {
	$type = 'related';
   $class = $type;

   $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
   $image = 'related_products_list';
   $title = __('Related Products');
   $items = $block->getItems();
   $limit = 0;
   $shuffle = 0;

   $showWishlist = true;
   $showCompare = true;
   $showCart = true;
   $templateType = null;
   $description = false;
}
  
?>
<?php if ($exist):?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<section class="<?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php else: ?>
<section class="<?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php endif; ?>
<?php else: ?>
<section class="<?php echo $class; ?>">
   <?php endif; ?>
	<div class="title-product-heading related-heading">
		<h2><?php echo __('You may be interested(e) by:'); ?></h2>
	</div>
	<div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading">
		<div class="product-grid">
			<div id="relate_product">
			<div class="row">
				<?php $iterator = 1; ?>
				<?php 
					$i = 0;
					$rows = 1;
				?>
				<?php foreach ($items as $_item): ?>
				<?php $available = ''; ?>
				<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
				<?php if (!$_item->getRequiredOptions()): ?>
				<?php $available = 'related-available'; ?>
				<?php endif; ?>
				<?php endif; ?>
			<?php
					$productImage = $block->getImage($_item, $image);
			?>	
				<?php if ($i++%$rows==0) { ?>
					<div class="item col-sm-3">
				<?php } ?>
					<div class="product-item">
						<div class="item-inner">
							<div class="new-sale-label">
								<?php
									$specialprice = $_item->getSpecialPrice();
									$specialPriceFromDate = $_item->getSpecialFromDate();
									$specialPriceToDate = $_item->getSpecialToDate();

									$today = time();

									if ($specialprice) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
											<span class="label-product label-sale">
													<?php echo __('Sale'); ?>
											</span>
										<?php }
									}
									?>

									<?php
									$now = date("Y-m-d");
									$newsFrom = substr($_item->getNewsFromDate(), 0, 10);
									$newsTo = substr($_item->getNewsToDate(), 0, 10);

									if ($newsTo != '' || $newsFrom != '') {
									if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
											<span class="label-product label-new">
												<?php echo __('New'); ?>
											</span>
									<?php }
									} ?>
							</div>
						<div class="product-photo">
							<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
								<span class="image0 image-switch">
									<?php echo $productImage->toHtml(); ?>
								</span>
								<span class="image1 image-switch">
									<?php echo $productImageThumb->toHtml(); ?>
								</span>
							</a>
							<div class="actions">
							<ul class="add-to-links">
								<li>
									<div class="actions-primary">
									<?php if ($_item->isSaleable()): ?>
									<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
									<button class="tooltip-toggle action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
									<span class="tooltip-content"><?php echo __('Add to Cart') ?></span>
									</button>
									<?php else: ?>
									<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
								   $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
								   ?>
									<button class="btn btn-add-to-cart tooltip-toggle"
									   data-post='<?php echo $postData; ?>'
									   type="button" title="<?php echo __('Add to Cart') ?>">
									<span class="tooltip-content"><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
									</button>
									<?php endif; ?>
									<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
											<button class="btn btn-add-to-cart tooltip-toggle"><span class="tooltip-content"><?php /* @escapeNotVerified */ echo __('In stock') ?></span></button>
										<?php else: ?>
											<button class="btn btn-add-to-cart tooltip-toggle"><span class="tooltip-content"><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></button>
										<?php endif; ?>
									<?php endif; ?>
								</div>
								</li>
							</ul>
								
							</div>
						</div>
						<div class="product-info">
							<p class="product-name">
								<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
								<?php echo $block->escapeHtml($_item->getName()) ?></a>
							</p>
							<?php echo $block->getProductPrice($_item); ?>
							<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
								
												
						</div>
					</div> 
				</div>
				<?php if($i%$rows==0 || $i == count($items)) { ?> 
				</div> 
				<?php } ?>
				<?php endforeach ?>
				</div> 
			</div>
		</div>
    </div>

</section>
<?php endif;?>