<div class="popup_avaiable">
	<?php
	$qty = $block->getQtyP()?$block->getQtyP():1;
	$_imgHelper = $this->helper('Themevast\Themevast\Helper\ImageP');
	$_themeHelper = $this->helper('Themevast\Themevast\Helper\Data');
	$_checkoutHelper=$this->helper('Magento\Checkout\Helper\Data');
	$product=$block->getProducts();
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
	$currencysymbol = $objectManager->get('Magento\Directory\Model\Currency');
	$symbol = $currencysymbol->getCurrencySymbol();
	$subTotal = (int)$cart->getQuote()->getSubtotal();
	$width = $subTotal/90*100 . '%';
	$grandTotal = $cart->getQuote()->getGrandTotal();
	$productUrl = $product->getProductUrl();
	$enable_image = true;
	if($enable_image) {
		$image_width  = 180;
		$image_height = 200;
		$_image = $_imgHelper->getImg($product, $image_width, $image_height, 'category_page_grid');
	}
	
	?>
	<div class="product_ajax">
		<?php if($enable_image && $_image) { ?>
			<div class="product_image">
				<a href="<?php echo $productUrl; ?>" title="<?php echo addslashes($_image->getLabel()); ?>"><img src="<?php echo $_image->getUrl(); ?>" alt="<?php echo addslashes($_image->getLabel()); ?>" /></a>
			</div>	
		<?php } ?>
		<div class="popup-details">
			<span class="alert_successful"><i class="fa fa-check" aria-hidden="true"></i><?php echo __("Successful!");?></span>
			<p>&nbsp;&quot;<?php echo $product->getName(); ?>&quot;&nbsp;<?php echo __("has been added ");?><a class="view_cart" href="<?php echo $this->helper('Magento\Checkout\Helper\Cart')->getCartUrl(); ?>"><?php echo __("Your cart");?></a></p>
		</div>
	</div>
</div>