<?php
$element = $this->getElement();
$block   = $this->getLayout()->createBlock(\Magento\Framework\View\Element\Template::class)->setTemplate('Magento_Search::form.mini.phtml');
$html    = $block->toHtml();
$html    = str_replace('search_mini_form', 'search_mini_form' . uniqid() . time(), $html);
$html    = str_replace('<input', '<input placeholder="' . $element->getData('placeholder') . '"', $html);
echo $html;