<?php
use \Magento\Framework\Stdlib\StringUtils;
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Themevast\Blog\Block\Sidebar\Recent
 */
?>

<?php

	$stringFilter = new \Magento\Framework\Stdlib\StringUtils;
	$enable = $this->getConfig('enable_frontend');
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('default');
	$show_next_back = $this->getConfig('show_next_back');
	$show_navigation_control = $this->getConfig('show_navigation_control');
	$title = $this->getConfig('title');
	$helperTheme = $this->helper('Themevast\Themevast\Helper\Image');

	$show_navigation_control = $this->getConfig('show_navigation_control');

	$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count() && $enable) { ?>
<div class="block-posts-slider blog-preload" data-bind="scope: 'recemt-posts'">
	<div class="container">
	<div class="block-title title-blog-heading">
		<strong><?php echo __($title) ?></strong>
	</div>
		<div class="owl-container">
			<div class="block-content">
				<div class="owl-carousel">
					<div class="blogFirst_loading"></div>
					<?php
						if(!$rows = $this->getConfig('rows'))
							$rows = 1;
						?>
					<?php $i=0; foreach ($_postCollection as $_post) { ?>
					<?php if($i %$rows == 0) echo "<div class='rows-item clearfix'>"; ?>
						<div class="blog-item">
								<div class="item-inner">
									<div class="blog-image clearfix">
										<a href="<?php echo $_post->getPostUrl() ?>">
											<?php $linkPost = $helperTheme->resize($_post->getThumbnailimage(),480,480);
											?>
											<img src="<?php echo $linkPost ?>" alt=""/>
										</a>
										<?php 
											$date = $_post->getPublishTime();
										?>
									</div>
									<div class="blog-content">
										<div class="meta-blog">
									        <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
												<div class="post-categories">
													<?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
													<a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
													<?php if ($n==1) {break;} ?>
													<?php } ?>
												</div>
											<?php } ?>
											<?php 
												$date = $_post->getPublishTime();
											?>
											<div class="date-time">
												<span><?php echo __(date("M", strtotime($date))) ?></span>
												<span><?php echo __(date("d", strtotime($date))) ?>,</span>
												<span><?php echo __(date("Y", strtotime($date))) ?></span>
											</div>
										</div>
										<h3 class="blog-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a></h3>
										<div class="read_more"><a href="<?php echo $_post->getPostUrl() ?>"><?= /* @escapeNotVerified */ __('Read the story ') ?><i class="fa fa-caret-right"></i></a></div>
									</div>
								</div>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</div>"; ?>                  
					<?php } ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>
				</div>
			
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'themevast/owl'
	], function ($) {
		'use strict';
		setTimeout(function () {
				jQuery(".block-posts-slider").removeClass('blog-preload');
				jQuery('.blogFirst_loading').remove();
				blogSlider();
		}, 500);
		function blogSlider() {
			jQuery(".block-posts-slider .owl-carousel").owlCarousel({
				autoplay :<?php echo $auto==1 ? 'true':'false' ?>,
				items : 3,
				smartSpeed : <?php echo $speed ?>,
				dotsSpeed : <?php echo $speed ?>,
				rewindSpeed : <?php echo $speed ?>,
				nav : <?php echo $show_next_back==1 ? 'true' : 'false';?>,
				autoplayHoverPause : true,
				dots :<?php echo $show_navigation_control==1 ? 'true':'false' ;  ?>,
				scrollPerPage:true,
				navText: ['<i class="envy-icon envy-icon-left"></i>','<i class="envy-icon envy-icon-right"></i>'],
				margin: 30,
				responsive: {
				0: {
					items: 1,
				},
				480: {
					items: 1,
				},
				768: {
					items: 2,
				},
				991: {
					items: 2,
				},						
				1200: {
					items: 3,
				}
			 }
			});
		}
	});
</script>
<?php } ?>