<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort by:') ?></label>
    <div class="sorter-options">
        <span class="sorter-current" data-mage-init='{"dropdown":{}}' data-toggle="dropdown"><?php echo $this->getCurrentOrder(); ?></span>
            <div class="sorter-control" data-target="dropdown">
                <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                    <a href="<?php echo $block->getPagerUrl("product_list_order=".$_key) ?>"
                        <?php if ($block->isOrderCurrent($_key)): ?>
                            class="selected"
                        <?php endif; ?>
                        >
                        <?php echo $block->escapeHtml(__($_order)) ?>
                    </a>
                <?php endforeach; ?>
            </div>
    </div>
    
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
