<?php 
//ducdevphp@gmail.com
use Magento\Framework\App\Action\Action;
$cattabHelper = $this->helper('Themevast\Categorytab\Helper\Data');
$_productCollection = $this->getData('productCollection');
$_bestsellerCollection = $this->getData('bestsellerCollection');
$rows = $block->getConfig('row',1);
$_collectionSize = $_productCollection->count();
$_imgHelper = $this->helper('Themevast\Categorytab\Helper\Image');
$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
$image = 'new_products_content_widget_grid';
$type = 'widget-new-grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
$showWishlist = $block->getConfig('wishlist',0);
$showCompare = $block->getConfig('compare',0);
$showCart = $block->getConfig('addtocart',0);
$rightClass = '';
$leftClass='';
if($_bestsellerCollection && $_bestsellerCollection->count()){
$leftClass="col-sm-12 col-md-8 col-left";
$rightClass = "col-sm-12 col-md-4 col-right";
}
$banner_product_best = $block->getConfig('banner_product_best');
$banner_product_cat1 = $block->getConfig('banner_product_cat1');
$banner_product_cat2 = $block->getConfig('banner_product_cat2');
//$cmsblock2 = $this->getConfig('cmsblock2');
//$html = $this->getCmsBlockModel()->load($cmsblock2)->getContent();
//$html = $cattabHelper->filter($html);
?>
<?php if($_collectionSize<1){?>
	<div class="message info empty">	
		<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
	</div>
<?php }?>

<!--dev themevast-->
<?php if($leftClass):?>
	<div class="<?php echo $leftClass?>">
<?php endif;?>
<div class="product-category">
 <?php if($banner_product_cat1):?>
		<p class="banner-category"><img src ="<?php echo $banner_product_cat1 ?>" alt ="<?php echo __('Banner category Top') ?>"/></p> 
 <?php endif; ?>
<div class="owl-carousel cattab_owl product-items">
		<?php $i=0; foreach($_productCollection as $_item): 
		$productImage = $block->getImage($_item, $image);
		$i++;?>
			<?php if($i % $rows == 1 || $rows == 1):?>
				<div class="cattab_item item product-list-item">
			<?php endif;?>
					<div class="product-item">
						<div class="product-item-info">
							<?php // Product Image ?>
							<div class="product-images">
								<!--- End -->
								<div class="new-sale-label">
									<?php
									$specialprice = $_item->getSpecialPrice();
									$specialPriceFromDate = $_item->getSpecialFromDate();
									$specialPriceToDate = $_item->getSpecialToDate();

									$today = time();
									if ($specialprice) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
											<span class="label-product label-sale"><?php echo __('Sale'); ?></span>
										<?php }
									}
									?>
									<?php
									$now = date("Y-m-d");
									$newsFrom = substr($_item->getNewsFromDate(), 0, 10);
									$newsTo = substr($_item->getNewsToDate(), 0, 10);

									if ($newsTo != '' || $newsFrom != '') {
									if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
											<span class="label-product label-new"><?php echo __('New'); ?></span>
									<?php }
									} ?>
								</div>
	                            <!--- End -->
								<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
										<?php echo $productImage->toHtml(); ?>
								</a>
								<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
									
									<a href="#"
										class="action towishlist"
									   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
									   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
									   data-action="add-to-wishlist"
									   role="button">
										<i class="fa fa-heart"></i>
									</a>
									
								<?php endif; ?>
								<div class="quickview-product">
	                                <a  data-role="quickview-button" data-id="<?php echo $_item->getId(); ?>" href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_item->getId()) ?>" title="" class="ajax diamond quick-view" data-placement="top" data-original-title="<?php echo ('Quick view') ?>">
	                                <?php echo $block->escapeHtml(__('Quick View')); ?>
	                                </a>
	                            </div>
	                            <div class="product-group-details">
	                            	<?php if ($templateType): ?>
										<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
									<?php endif; ?>
									<strong class="product name product-item-name">
										<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php echo $block->getProductUrl($_item) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</strong>
									<?php
										echo $block->getProductPrice($_item);
									 ?>
									 <?php if ($showCart): ?>
										<div class="actions-primary">
											<?php if ($_item->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_item); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item); ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button class="action tocart primary" type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>" >
														<span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_item->getIsSalable()): ?>
													<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></button>
												<?php else: ?>
													<button class="btn btn-add-to-cart"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></button>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
	                            </div>
							</div>
							<div class="product details product-item-details">
								<strong class="product name product-item-name">
									<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
									   href="<?php echo $block->getProductUrl($_item) ?>"
									   class="product-item-link">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</strong>
								<?php
									echo $block->getProductPrice($_item);
								 ?>
								<a class="shop-now" href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"><?php echo $block->escapeHtml(__('Shop now')); ?><i class="fa fa-caret-right"></i></a>
							</div>
						</div>
						
	                    
						
						
					</div>
			 <?php if($i % $rows == 0 || $i == $_collectionSize):?>
				</div>
			<?php endif;?>
		<?php endforeach;?>
	</div>
<?php if($banner_product_cat2): ?>
		<p><img src ="<?php echo $banner_product_cat2 ?>" alt ="<?php echo __('Banner category Bottom') ?>"/></p> 
<?php endif; ?>
</div>
<?php if($leftClass):?>
	</div>
<?php endif;?>

<!--bestseller-->
<?php if($rightClass) :?>
	<?php if($_bestsellerCollection && $_bestsellerCollection->count()):?>
	<?php $rowbs=1;$j=0;$_collectionBestSize = $_bestsellerCollection->count();?>
	<div class="<?php echo $rightClass?>">
		<div class="cattab_bestseller">
			<div class="title-product-heading title-catbest-heading">
				<h2><?php echo __('Bestseller') ?></h2>
			</div>
			<?php if($banner_product_best):?>
				<p> <img src ="<?php echo $banner_product_best?>"  alt ="<?php echo __('Banner Bestseller') ?>"/> </p> 
			<?php endif; ?>
			<div class="owl-carousel owl list-products">
			<?php foreach($_bestsellerCollection as $_product) { 
				$productImage = $block->getImage($_product, $image);
			?>
			<?php if($j++%$rowbs==0) { ?> <div class="item clearfix"> <?php } ?>
			<div class="product-list-item">
				<div class="product-photo">
					<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
						<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1');?>
						<span class="image0 image-switch">
							<?php echo $productImage->toHtml(); ?>
						</span>
						<span class="image1 image-switch">
							<?php echo $productImageThumb->toHtml(); ?>
						</span>
					</a>
				</div>
				<div class="product-info">
					<p class="product-name">
							<a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
							   href="<?php echo $block->getProductUrl($_product) ?>"
							   class="product-item-link">
								<?php echo $block->escapeHtml($_product->getName()) ?>
							</a>
					</p>
					<?php if ($templateType): ?>
						<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
					<?php endif; ?>
					 <?php
						echo $block->getProductPrice($_product);
					 ?>
				</div>
			</div>
			<?php if($j%$rowbs==0 || $j == count($_collectionBestSize)) { ?> </div> <?php }?>
			<?php 
				}
			?>
			</div>
		</div>
	</div>
	<?php endif;?>
<?php endif;?>
<!-- end bestseller-->

<?php if (!$block->isRedirectToCartEnabled()) : ?>
	<script type="text/x-magento-init">
	{
		"[data-role=tocart-form], .form.map.checkout": {
			"catalogAddToCart": {}
		}
	}
	</script>
<?php endif; ?>
