
<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <div class="block-title">
        <strong><?php echo __('Recent Posts') ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>
            <div class="item">
                <div class="blog-image">
                     <a href="<?php echo $_post->getPostUrl() ?>">
                         <img src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>"/>
                    </a>               
                </div>
                <div class="blog-recent-info">
                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                    <div class="item post-categories">
                        <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                        <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                        <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                        <?php } ?>
                    </div>
                <?php } ?>
                <div class="time-recent">
                    <?php 
                        $date = $_post->getPublishTime();
                    ?>
                    <div class="date-time">
                        <span class="month"><?php echo __(date("M", strtotime($date))) ?></span>
                        <span class="date"><?php echo __(date("d", strtotime($date))) ?></span>
                        
                    </div>
                </div>
                <div class="title">
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()) ?>
                    </a>
                </div>
                
                
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<?php } ?>