<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<div class="block_contact_container">
    <div class="contact_top">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_map')->toHtml();?>
    </div>
    <div class="contact_bottom">
        <div class="row">
            <div class="col-sm-6">
                 <div class="block-contact-info">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block_address_contact')->toHtml();?>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="block-contact-form">
                    <form class="form-contact"
                          action="<?= $block->escapeUrl($block->getFormAction()) ?>"
                          id="contact-form"
                          method="post"
                          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                          data-mage-init='{"validation":{}}'>
                        <fieldset class="fieldset">
                            <div class="group-field row">
                                <div class="col-md-6">
                                    <div class="field name required">
                                        <div class="control">
                                            <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Your name')) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="field email required">
                                        <div class="control">
                                            <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Your email')) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field telephone">
                                <div class="control">
                                    <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Phone number')) ?>" class="input-text" type="text" />
                                </div>
                            </div>
                            <div class="field comment required">
                                <div class="control">
                                    <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Your message here!')) ?>" class="input-text" cols="10" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                                </div>
                            </div>
                            <?= $block->getChildHtml('form.additional.info') ?>
                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <input type="hidden" name="hideit" id="hideit" value="" />
                                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                                    <span><?= $block->escapeHtml(__('Send Message')) ?></span>
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
