
<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts" data-bind="scope: 'recemt-posts'">
    <div class="block-title">
        <strong><?php echo __('Lastest Posts') ?></strong>
    </div>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>
            <div class="item">
                <div class="blog-image">
                     <a href="<?php echo $_post->getPostUrl() ?>">
                         <img src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>"/>
                    </a>               
                </div>
                <div class="blog-recent-info">
                    <div class="time-recent">
                        <?php 
                            $date = $_post->getPublishTime();
                        ?>
                        <div class="date-time">
                            <span class="month"><?php echo __(date("M", strtotime($date))) ?></span>
                            <span class="date"><?php echo __(date("d", strtotime($date))) ?></span>
                            <span class="year"><?php echo __(date("Y", strtotime($date))) ?></span>
                        </div>
                    </div>
                    <div class="title">
                        <a class="post-item-link"
                           href="<?php echo $_post->getPostUrl() ?>">
                            <?php echo $block->escapeHtml($_post->getTitle()) ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<?php } ?>