<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
		<div class="post-images">
			<a href="<?php echo $_post->getPostUrl() ?>">
				<img src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>"/>
			</a>
            <?php echo $this->getInfoHtml() ?>
            <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
            <div class="item post-categories">
                <?php $n = 0; foreach($_post->getParentCategories() as $ct) { $n++; ?>
                <a title="<?php echo $block->escapeHtml($ct->getTitle()) ?>" href="<?php echo $ct->getCategoryUrl() ?>"><?php echo $block->escapeHtml($ct->getTitle()) ?></a>
                <?php if ($n != $_categoriesCount) { ?>, <?php } ?>
                <?php } ?>
            </div>
            <?php } ?>
		</div> 
        <div class="post-content">
            <div class="post-title-holder clearfix">
                <h2 class="post-title">
                    <a class="post-item-link"
                       href="<?php echo $_postUrl ?>">
                        <?php echo $_postName; ?>
                    </a>
                </h2> 
            </div>
            <?php if ($_author = $_post->getAuthor()) { ?>
                 <div class="post-author">
                 <span class="label">&nbsp;</span>
                 <span class="value">
                 <?php echo $block->escapeHtml($_author->getTitle()) ?>
                 </span>
                 </div>
                <?php } ?>
            <div class="post-description">
                <?php echo $block->getContent() ?>
                <div class="clear"></div>
            </div>
            <div class="post-header clearfix">
                <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                    <a class="addthis_button_facebook"></a>
                    <a class="addthis_button_twitter"></a>
                    <a class="addthis_button_email"></a>
                    <a class="addthis_button_compact"></a>
                </div> 
            </div>
        </div>
        
        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>