<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ ?>
	<?php $_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="tv-featuredproduct">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="tv-product-heading tv-featured-heading"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="tv-featured-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>	
			<div class="row">
				<ul class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<li class='item featuredproductslider-item'>"; ?>

							<div class="product-item">
								<?php
									$specialprice = $_product->getSpecialPrice();
									$specialPriceFromDate = $_product->getSpecialFromDate();
									$specialPriceToDate = $_product->getSpecialToDate();

									$today = time();

									if ($specialprice) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
											<div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo __('Sale'); ?>
												</span>
											</div>
										<?php }
									}
									?>

									<?php
									$now = date("Y-m-d");
									$newsFrom = substr($_product->getNewsFromDate(), 0, 10);
									$newsTo = substr($_product->getNewsToDate(), 0, 10);

									if ($newsTo != '' || $newsFrom != '') {
									if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
											<div class="label-product label-new">
												<span class="new-product-icon"><?php echo __('New'); ?></span>
											</div>
									<?php }
									} ?>
														
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								
								<a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php echo $_product->getProductUrl() ?>">
										<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</strong>

								<?php if( $this->getConfig('show_price') ): ?>
									 <?php  echo $block->getProductPrice($_product) ?>
								<?php endif; ?>

								<div class="product-ratting">
									<?php if($this->getConfig('review')): ?>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
									<?php endif; ?>
								</div>
										
								<div class="actions clearfix">
									<div class="action-inner">
										<?php if ($this->getConfig('addtocart')) { ?>
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php  echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php  echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php  echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
															class="action tocart primary">
														<span><?php  echo __('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php  echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
										<?php }?>	
										
										<?php if( $this->getConfig('addtowishlist') || $this->getConfig('addtocompare') ){?>
											<ul class="add-to-links">
											<?php if( $this->getConfig('addtowishlist')): ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
													<li>
														<a href="#"
														   class="action towishlist"
														   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
														   data-action="add-to-wishlist"
														   role="button">
															<span><?php  echo __('Add to Wish List') ?></span>
														</a>
													</li>
													<?php endif; ?>
												<?php endif; ?>
						
											<?php if( $this->getConfig('addtocompare')): ?>
											<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<li><a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php  echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<span><?php  echo __('Add to Compare') ?></span>
													</a>
												</li>
											<?php endif; ?>
											</ul>
										<?php }?>
									</div>
								</div>
								<?php if( $this->getConfig('description')){?>
									<div class="ma-desc">
										 <?php echo $block->getProductDetailsHtml($_product); ?>		                    
									</div>
								<?php }?>
							<?php $i++;?>
						</div>
						<?php if($i %$rows == 0) echo "</li>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>                
				</ul>
			</div>
		<?php if (!$block->isRedirectToCartEnabled()) : ?>
			<script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
			</script>
		<?php endif; ?>
			<script>
				require([
					'jquery',
					'mage/mage',
					'themevast/owl'
				], function ($) {
					'use strict';

					jQuery(".tv-featuredproduct .owl").owlCarousel({
						autoPlay : false,
						items : 4,
						itemsDesktop : [1199,4],
						itemsDesktopSmall : [980,3],
						itemsTablet: [768,2],
						itemsMobile : [479,1],
						slideSpeed : 500,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : true,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
					});
				});
			</script>
	<?php endif; ?>
	</div>
 
<?php } ?>