<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="newsletter">
    <form class="form subscribe"
        novalidate
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
        <div class="field newsletter">
            <!-- <label class="label-newsletter" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label> -->
            <div class="control">
                <input name="email" type="email" id="newsletter"
                            placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                            data-validate="{required:true, 'validate-email':true}"/>
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                <span><?= $block->escapeHtml(__('Sign up !')) ?></span>
            </button>
            </div>
        </div>

    </form>
</div>
