<?php
$builderConfig     = $this->getBuilderConfig();
$id                = $this->getHtmlId();
$targetId          = $this->getTargetId();
$additionalClasses = $this->getAdditionalClasses();
$data              = [
	'allowed_types' => ['row'],
	'targetId'      => $targetId
];
$url = $this->getUrl('mgzpagebuilder/product/wysiwyg');
?>
<div class="mgz-builder <?= $additionalClasses ?>" id="<?= $id ?>" ng-controller="magezonBuilderCtrl">
	<magezon-builder profile="profile"></magezon-builder>
</div>
<style id="<?= $targetId ?>-styles"></style>
<script type="text/javascript">
	window.magezonBuilder = {
		viewFileUrl: '<?= $this->getBuilderViewFileUrl() ?>'
	}
	require([
		'jquery',
		'angular',
		'magezonBuilder',
		'api-check'
		<?= $this->getModulePaths() ?>
	], function($, angular, mgzBuilder, apiCheck) {
		var parent = $('#<?= $targetId ?>').closest('.admin__field');
		if (parent.parent().hasClass('admin__field-control')) {
			parent.parent().addClass('magezon-builder-active-wrapper');
			var width = parent.parent().parent().width() * .72;
			parent.parent().width(width);
			$('#<?= $id ?>').width(width);
		}
		apiCheck.globalConfig.disabled = true;
		var builderConfig = <?= $this->getSerializedBuilderConfig() ?>;
		window.builderConfig = builderConfig;
		var app = angular.module('<?= $id ?>', ['magezonBuilder' <?= $this->getModuleKeys() ?>], function config(magezonBuilderConfigProvider, formlyConfigProvider) {
			// formlyConfigProvider.disableWarnings = true;
			// formlyConfigProvider.extras.removeChromeAutoComplete = true;
  	// 		formlyConfigProvider.extras.explicitAsync = true;
			_.each(builderConfig.groups, function(elem) {
				magezonBuilderConfigProvider.registerGroup(elem.type, elem);
			});
			_.each(builderConfig.elements, function(elem) {
				magezonBuilderConfigProvider.registerElement(elem.type, elem);
			});
			magezonBuilderConfigProvider.processAllowTypes();
			_.each(builderConfig.directives, function(directive, name) {
				magezonBuilderConfigProvider.registerDirectives(name, directive);
			});
		}).run(['$rootScope', '$log', '$window', 'magezonBuilderService', 'magezonBuilderConfig', 'elementManager', 'formlyConfig', '$sce', function($rootScope, $log, $window, magezonBuilderService, magezonBuilderConfig, elementManager, formlyConfig, $sce) {
			///formlyConfig.disableWarnings     = true;
			elementManager.registerElements(magezonBuilderConfig.elements);
			elementManager.groups            = magezonBuilderConfig.groups;
			$rootScope.profile               = <?= json_encode($data) ?>;
			$rootScope.ajaxData              = {};
			$rootScope.magezonBuilderService = magezonBuilderService;
			$rootScope.elementManager        = elementManager;
			$rootScope.$log                  = $log;
			$rootScope.currentProfile        = {};
			$rootScope.$window               = $window;
			$rootScope.parseInt              = parseInt;
			$rootScope.parseFloat            = parseFloat;
			$rootScope.builderConfig         = builderConfig;
			$rootScope.$sce                  = $sce;
			$rootScope.rootId                = '<?= $id ?>-wrapper';
		}]);
		app.config(['$compileProvider', '$httpProvider', function($compileProvider, $httpProvider) {
			// $compileProvider.commentDirectivesEnabled(false);
			// $compileProvider.cssClassDirectivesEnabled(false);
			// $compileProvider.debugInfoEnabled(false);
			// $httpProvider.useApplyAsync(1000);
			// $httpProvider.useLegacyPromiseExtensions = false;
		}]);
		app.controller('magezonBuilderCtrl', ['$scope', '$rootScope', '$timeout', function($scope, $rootScope, $timeout) {
			var parent = $('#<?= $targetId ?>').closest('.admin__field');
			parent.addClass('mgz-builder-wrapper');
			parent.addClass('<?= $id ?>-wrapper');
			if (parent.parent().hasClass('admin__control-grouped')) {
				parent.parent().addClass('mgz-builder-grouped-wrapper');
			}
			if (builderConfig.profile.switchMode) {
				parent.find('.admin__field-control').eq(0).prepend('<button type="button" class="mgz-builder-action-btn mgz-builder-active-btn"><i class="mgz-icon mgz-icon-magezon-pagebuilder"></i><?= __('Active Magezon Page Builder') ?></button><button type="button" class="mgz-builder-action-btn mgz-builder-deactive-btn"><i class="mgz-icon mgz-icon-magezon-pagebuilder"></i><?= __('Deactivate Magezon Page Builder') ?></button><button type="button" onclick="magezonPageBuilderWysiwygEditor.open(\'<?= $url ?>\', \'<?= $targetId ?>\')" class="mgz-builder-wysiwyg-btn action-default"><span><?= __('WYSIWYG Editor') ?></span></button>');
				$('.<?= $id ?>-wrapper .mgz-builder-active-btn').click(function(e) {
					$rootScope.$broadcast('importShortcode');
					$('.<?= $id ?>-wrapper').addClass('mgz-deactive-builder');
					$('.<?= $id ?>-wrapper').removeClass('mgz-active-builder');
				});
				$('.<?= $id ?>-wrapper .mgz-builder-deactive-btn').click(function(e) {
					$('.<?= $id ?>-wrapper').addClass('mgz-active-builder');
					$('.<?= $id ?>-wrapper').removeClass('mgz-deactive-builder');
				});
			}
		}]);
		<?php
			if (isset($builderConfig['controllers'])) {
				foreach ($builderConfig['controllers'] as $key => $path) { ?>
					require(['<?= $path ?>'], function(_controller) {
						app.controller('<?= $key ?>', _controller);
					});
				<?php }
			}
		?>
		require(['domReady!'], function (document) {
			angular.bootstrap(document.getElementById('<?= $id ?>'), ['<?= $id ?>'], {
				//strictDi: true
			});
		});
	});
</script>